services:
  db:
    build: .
    image: metropolis-library-db:1.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: library123
      POSTGRES_DB: library

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
